version: '3.1'

services:

  db:
    image: postgres
#    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Chat
    ports:
      - "5432:5432"
    volumes:
      - ./store:/var/lib/postgresql/data

  adminer:
    image: dpage/pgadmin4
#    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"